### ISSUE TITLE
RestSharp package utilized is out of date

### ISSUE THREAD

**Issue by dragnldy** [BetterImpact/ApiClient#1]
The version of the RestSharp package utilized in this demo has been deprecated as there apparently are severe security vulnerabilities associated with it.  The newest version as of May 2022, V107, has breaking changes that cause this code to fail to compile.  For example, all interfaces have been removed from the package.  I can perform the migration to the new package but you might want to update your demo solution

**Comment by pmcquay** [comment]
It has been updated!
